// #1 copy json to clipboard
// #2 crtl + p
// #3 >P Json as types
// Generated by https://quicktype.io

export interface ExampleJSON {
  users: User[];
}

export interface User {
  localId: string;
  email: string;
  displayName: string;
  photoUrl: string;
  passwordHash: string;
  emailVerified: boolean;
  passwordUpdatedAt: number;
  providerUserInfo: ProviderUserInfo[];
  validSince: string;
  lastLoginAt: string;
  createdAt: string;
}

export interface ProviderUserInfo {
  providerId: string;
  displayName: string;
  photoUrl: string;
  federatedId: string;
  email: string;
  rawId: string;
}
